### PR TITLE
Working with text files

### PR DESCRIPTION
**Pull request by Clement-Mathobela**

### CODE REVIEW

**Review by lehlohonolotladi — APPROVED** [review]
Nice one

**Review by lehlohonolotladi — APPROVED** [review]
Nice

**Review by SeabelaSHEDO — APPROVED** [review]

**Comment by SeabelaSHEDO** [comment]
cool

**Comment by lehlohonolotladi** [comment]
Great

**Comment by lehlohonolotladi** [comment]
cool

**Review by Clement-Mathobela — COMMENTED** [review]
Cool

**Pull request merged**
